from arraystubs import Vec, dbl, flt

def axpy[T: (dbl, flt)](a: float, x: Vec[T], y: Vec[T]) -> Vec[T]: ...
def mult[T: (dbl, flt)](a: float, x: Vec[T]) -> None: ...
def sum_as_string(a: int, b: int) -> str: ...
